language: python
dist: trusty
python:
    - "2.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-5
      - libblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin
env:
     - PARA=no
install:
     - ./configure --enable-parallel=$PARA --with-netlib
     - make pw pp ph neb vdw_kernels
script:
    - make travis
git:
  depth: 3
